version: "3"
services:
    kafka1:
        image: confluentinc/cp-kafka
        container_name: kafka1
        hostname: kafka1
        ports:
            - "9092:9092"
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_LISTENERS: "INTERNAL://kafka1:29092,CONTROLLER://kafka1:29093,EXTERNAL://0.0.0.0:9092"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:29092,EXTERNAL://localhost:9092"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093,2@kafka2:29093,3@kafka3:29093"
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
            CLUSTER_ID: "ciWo7IWazngRchmPES6q5A=="
            KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
        volumes:
            - ./kafka1:/var/lib/kafka/data
        networks:
            - ${GLOBAL_NETWORK:-kafka}
    kafka2:
        image: confluentinc/cp-kafka
        container_name: kafka2
        hostname: kafka2
        ports:
            - "9093:9093"
        environment:
            KAFKA_NODE_ID: 2
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_LISTENERS: "INTERNAL://kafka2:29092,CONTROLLER://kafka2:29093,EXTERNAL://0.0.0.0:9093"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka2:29092,EXTERNAL://localhost:9093"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093,2@kafka2:29093,3@kafka3:29093"
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
            CLUSTER_ID: "ciWo7IWazngRchmPES6q5A=="
            KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
        volumes:
            - ./kafka2:/var/lib/kafka/data
        networks:
            - ${GLOBAL_NETWORK:-kafka}
    kafka3:
        image: confluentinc/cp-kafka
        container_name: kafka3
        hostname: kafka3
        ports:
            - "9094:9094"
        environment:
            KAFKA_NODE_ID: 3
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_LISTENERS: "INTERNAL://kafka3:29092,CONTROLLER://kafka3:29093,EXTERNAL://0.0.0.0:9094"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka3:29092,EXTERNAL://localhost:9094"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093,2@kafka2:29093,3@kafka3:29093"
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
            CLUSTER_ID: "ciWo7IWazngRchmPES6q5A=="
            KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
        volumes:
            - ./kafka3:/var/lib/kafka/data
        networks:
            - ${GLOBAL_NETWORK:-kafka}
    schema-registry:
        image: confluentinc/cp-schema-registry
        container_name: schema-registry
        hostname: schema-registry
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka1:29092,kafka2:29092,kafka3:29092"
            SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
        depends_on:
            - kafka1
            - kafka2
            - kafka3
        networks:
            - ${GLOBAL_NETWORK:-kafka}
    kafka-ui:
        image: provectuslabs/kafka-ui
        ports:
            - 8083:8080
        environment:
            DYNAMIC_CONFIG_ENABLED: "true"
        depends_on:
            - kafka1
            - kafka2
            - kafka3
        networks:
            - ${GLOBAL_NETWORK:-kafka}
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: admin1234
            POSTGRES_USER: admin
        volumes:
            - ./postgre/data:/var/lib/postgresql/data
            - ./postgre/init/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - ${GLOBAL_NETWORK:-kafka}

networks:
    food-order-system:
        driver: bridge
