server:
    port: 8184

customer-service:
    customer-topic-name: customer-value

spring:
    jpa:
        open-in-view: false
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true
        username: admin
        password: admin1234
        driver-class-name: org.postgresql.Driver
    # sql:
    #     init:
    #         platform: postgres
    #         schema-locations: classpath:/init-schema.sql
    #         mode: always
    # kafka:
    #     producer:
    #       transaction-id-prefix: tx_
kafka-config:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    schema-registry-url-key: schema.registry.url
    schema-registry-url: http://localhost:8081
    num-of-partitions: 3
    replication-factor: 3

kafka-producer-config:
    key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
    value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
    compression-type: snappy
    acks: all
    batch-size: 16384
    batch-size-boost-factor: 100
    linger-ms: 5
    request-timeout-ms: 60000
    retry-count: 5
